#!/bin/bash

# Create a persistent volume.
#
# The calling environment must contain the required credentials for the target
# account.
#
# Parameters are:
#   Region.
#   My stack name.
#   Zone number.
#   Tag.
#   Size (GB)

set -e
set -o pipefail

region=${1:?"Missing region name"}
STACK_NAME=${2:?"Missing stack name"}
zone_number=${3:?"Missing zone number"}
tag=${4:?"Missing tag"}
size=${5:?"Missing volume size"}
shift 5

source ./functions

resource=volume
availability_zone=$(zone_number_to_name ${zone_number:?})

json_fragment << EODATA
{
  "AWSTemplateFormatVersion" : "2010-09-09",

  "Description" : "Define a persistent volume",
  "Resources" : {
    "$resource" : {
      "Type" : "AWS::EC2::Volume",
      "Properties" : {
	"AvailabilityZone" : "${availability_zone:?}",
	"Size" : "${size:?}",
	"Tags" : [
          { "Key" : "Name", "Value" : "${tag:?}" }
        ]
      }
    }
  },

  "Outputs" : {
    "VolumeId" : {
      "Description" : "Volume id",
      "Value" : { "Ref" : "$resource" }
    }
  }
}
EODATA

build_stack
