#!/bin/bash

set -e

blob=$(openssl rsa -in whispir_common.pem -pubout | grep -v '^---' | tr -d '\n')

import() {
	(
		# Set temporary credentials for this account
		source ./sts-assume-admin ${1:?}

		for region in ${2:?}
		do
			match=0
			for key in $(aws ec2 describe-key-pairs --region $region --query KeyPairs[*].KeyName --output text)
			do
				if [ "$key" = whispir_common ]
				then
					match=1
				fi
			done
			if [ $match = 0 ]
			then
				aws ec2 import-key-pair --region $region --key-name whispir_common --public-key-material $blob
			fi
		done
	)
}

awk -F'|' '/^\|\|/ || $7 ~ /^ *$/{next}{printf("import %s \"%s\"\n", $3, $7)}' < accounts |
while read line
do
	eval $line
done
